name: Anouncer
main: de.codeinfection.quickwango.Anouncer.Anouncer
version: "${project.version}"
authors:
  - "Quick_Wango"
softdepends:
  - Permissions
description: "Automaticly anounce text files to the server."
commands:
  anounce:
    usage: "/<command> <name>"
    description: "Anounces the content of a file"
  reloadanouncer:
    usage: "/<command>"
    description: "Reloads the Anouncer plugin"
softdepends:
  - Permissions