name: Anouncer
main: de.codeinfection.quickwango.Anouncer.Anouncer
version: "${project.version}"
author: "Quick_Wango"
commands:
  anounce:
    usage: "/<command> <name>"
    description: "Anounces the content of a file"
Soft-depends:
  - Permissions