name: Announcer
main: de.codeinfection.quickwango.Announcer.Announcer
version: "${project.version}"
website: "http://mc-portal.de"
authors:
  - "Quick_Wango"
description: "Automaticly announce text files to the server."
commands:
  announce:
    usage: "/<command> <name>"
    description: "Announces the content of a file"
  reloadannouncer:
    usage: "/<command>"
    description: "Reloads the Announcer plugin"
permissions:
  Announcer.*:
    description: "Allows the player to do everything"
    default: op
    children:
      Announcer.announce: true
      Announcer.reload: true
  Announcer.announce:
    description: "Allows the player to manually announce messages"
    default: op
  Announcer.reload:
    description: "Allows the player to reload this plugin"
    default: op