name: Anouncer
main: de.codeinfection.quickwango.Anouncer.Anouncer
version: "${project.version}"
author: "Quick_Wango"
commands:
  anounce:
    usage: "/<command> <name>"
    description: "Anounces the content of a file"
  reloadanouncer:
    usage: "/<command>"
    description: "Reloads the Anouncer plugin"
softdepends:
  - Permissions